package com.uptc.controller;

public enum Commands {
	C_ADD_PROCESS,C_EXECUTE_PROCESS,
	C_REPORT_FOR_STATUS_CHANGE_PROCESS,C_REPORT_BY_EXIT_STATE,
	C_REPORT_BY_READY_STATES,C_REPORT_BY_EXECUTE_STATES,
	C_REPORT_BY_LOCKED_STATES,C_REPORT_FOR_STATUS_CHANGE, C_CLOSE_APP,C_DELETTE_PROCESS,
	C_REPORT_BY_DESTROY_PROCESS,C_REPORT_BY_LAYOFF_PROCESS,C_REPORT_BY_RESUME_PROCESS,
	C_REPORT_BY_CONNECT_PROCESS, C_CLOSE_DIALOG, CONNECT_PROCESS, NEW_PRIORITY;
}
